### ISSUE TITLE
Stopping a previously running process and starting it with new inputs

### ISSUE THREAD

**Issue by aminrahman** [linksmart/device-gateway#46]
In my application, I am using DGW on a raspberry pi computer to PUT different amounts of light on a lamp (a simple LED). I use the PWM pin of Raspberry pi for this aim. In the related python code (which DGW calls) I have to put the <code>pwm.ChangeDutyCycle(x)</code> part of my code in an infinite loop so the PWM pin always has the required voltage for the lamp. This leads to a problem when I ask DGW to PUT a new amount for the light of the lamp. What happens is that the previous process is still running and DGW starts a new one. This makes my lamp blinking and over heats my Raspberry pi.
I have attached my python code and the config file.

[pythoncode.txt](https://github.com/linksmart/device-gateway/files/4186983/pythoncode.txt)
[jsonfile.txt](https://github.com/linksmart/device-gateway/files/4186984/jsonfile.txt)

**Comment by farshidtz** [comment]
Hi Amin,

Could you tell me which resource in the jsonfile (there are 4) is for the python script in question? Led or Ledlamp?

**Comment by aminrahman** [comment]
Hi Farshid,
It is Ledlamp.

**Comment by farshidtz** [comment]
I see that you are running the script as `task`. This way, your PUT request will never respond because the script doesn't exit.

First, change the device config to:
`conf/devices/ledlamp.json`
```json
{
  "name": "ledlamp",
  "ttl": 30,
  "resources": [
   {
     "type": "Resource",
     "name": "duty_cycle",
     "agent": {
     "type": "service",
     "exec": "python -u conf/devices/ledlamp.py"
    },
     "representation": {
        "text/plain": {}
      },
     "protocols": [
       {
       "type": "REST",
       "methods": [
          "PUT", "GET"
       ],
       "content-types": [
          "text/plain"
       ]
     }
    ]
   }
  ]
}
```
Note that I have renamed the device to `ledlamp` and resource to `duty_cycle`. Moreover, I changed the resource type to `service` and added `-u` flag to execute the script in unbuffered mode. I also added `GET` method for debugging.

When set to `service`, the script is executed as soon as you execute DGW.

Second, change your script to maintain the LED duty cycle in the background and continue taking user input in the foreground:
`conf/devices/ledlamp.py`
```python
import RPi.GPIO as GPIO
from time import sleep
from threading import Thread

led_pin = 13

user_input = input("") # wait for the first input

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(led_pin,GPIO.OUT)

pwm = GPIO.PWM(led_pin, 200)

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(led_pin,GPIO.OUT)
pwm = GPIO.PWM(led_pin, 0.5)
pwm.start(user_input)

def keep_on():
        while user_input != -1:
                print("Current value: %s" % user_input)
                pwm.ChangeDutyCycle(user_input)
                sleep(10)

# execute in a thread
thread = Thread(target= keep_on, args=())
thread.start()

# wait for more user input
while user_input != -1:
        user_input = input("")
        print("Current value: %s" % user_input)
        pwm.ChangeDutyCycle(user_input) # to set the value immediately

# wait for the thread to finish
thread.join(timeout=3) # timeout earlier instead of waiting for the sleep
```
Run it locally and try first. It should take values and stop when you enter -1.

This way, your script will be executed, waiting for the first user inputs via a PUT requests to `<endpoint>/ledlamp/duty_cycle`. Setting it to -1 will stop the script which may not be desired because won't be able to start it anymore.

You can also GET the current value to check if the value was set.

Hope that helps.

**Comment by aminrahman** [comment]
This is great!
Thank you so much.
